module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💊', '💫', '🍂', '🌟', '🎋', '😶‍🌫️', '🫀', '🧿', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/JvogBqBXhp94rVjFMxDQRi',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://i.ibb.co/4LSss7R/tourl-1766641720069.jpg',
    NEWSLETTER_JID: '120363403285845335@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: 'ꪜǫᴜᴇᴇɴ ꪻɪᴍᴀʟsʜᴀꪖ🧚‍♂️ᴍᴅ',
    OWNER_NAME: '𝚜𝚊𝚗𝚞 𝚡𝚍 𝚘𝚠𝚗𝚎𝚛',
    OWNER_NUMBER: '94703229057',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: '> ᴘᴏᴡᴇʀᴅ ʙʏ Qᴜᴇᴇɴ ɪᴍᴀʟꜱʜᴀ ᴍᴅ',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029VbC2V7k3QxS4uRS8cB1P,
};
